import ScrollReveal from "@/components/ScrollReveal";
import { Button } from "@/components/ui/button";
import {
  ArrowRight, Briefcase, FileSignature, FileText, GitCompare, Globe, Highlighter,
  Kanban, LayoutTemplate, Mic, Presentation, ScanSearch, SendHorizontal, Sparkles, Video,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useLocation } from "react-router-dom";

type Copy = { tagline: string; capabilities: string[] };
type AgentDef = { id: string; icon: LucideIcon; name: string; de: Copy; en: Copy; beta?: boolean };

const agents: AgentDef[] = [
  { id:"ai-cv-analyzer", icon:ScanSearch, name:"AI CV Analyzer", de:{tagline:"Analysiert CVs strukturiert, generiert automatisch Tags und Skills und erstellt eine einheitliche Darstellung von Werdegang und Ausbildung.",capabilities:["Tags, Skills, Kandidatentyp und Seniorität automatisch ableiten","Berufserfahrung, Ausbildung und Zusammenfassung strukturiert aufbereiten","Kandidaten-, Unternehmens- und Branchenangaben anonymisieren","Profile direkt für Suche, Listen und Matching nutzbar machen"]}, en:{tagline:"Analyzes CVs, automatically generates tags and skills, and creates a consistent structure for experience and education.",capabilities:["Automatically derive tags, skills, candidate type and seniority","Structure work experience, education and summaries","Anonymize candidate, company and industry information","Make profiles directly usable for search, lists and matching"]}},
  { id:"ai-candidate-match", icon:GitCompare, name:"AI Candidate Match", de:{tagline:"Bewertet die Passung von Kandidaten zu einem Mandat mit Score von 0 bis 100 und nachvollziehbarer Begründung.",capabilities:["Muss-Skills und Projektanforderungen gegeneinander prüfen","Score und Begründung am Kandidaten dokumentieren","Shortlists nach Relevanz priorisieren","Ergebnisse direkt in Folgeprozessen nutzen"]}, en:{tagline:"Evaluates candidate fit for a project with a 0–100 score and a transparent explanation.",capabilities:["Compare must-have skills with project requirements","Store score and reasoning with the candidate","Prioritize shortlists by relevance","Use results directly in downstream workflows"]}},
  { id:"ai-outreach-messages", icon:SendHorizontal, name:"AI Outreach Messages", de:{tagline:"Erstellt personalisierte, projektspezifische Active-Sourcing-Nachrichten für LinkedIn, Xing und Mailshots.",capabilities:["Ton, Länge und Aufbau individuell steuern","Projektinformationen automatisch einbeziehen","Personalisierte Entwürfe direkt aus Kandidaten- und Projektbezug erstellen","Texte vor dem Versand prüfen und anpassen"]}, en:{tagline:"Creates personalized, project-specific active sourcing messages for LinkedIn, Xing and email campaigns.",capabilities:["Control tone, length and structure","Automatically include project information","Create personalized drafts from candidate and project context","Review and edit messages before sending"]}},
  { id:"ai-dossier-highlights", icon:Highlighter, name:"AI Dossier Highlights", de:{tagline:"Erstellt kompakte Highlights zur Passung von Kandidat und Projekt.",capabilities:["Relevante Erfahrung statt vollständiger CV-Lektüre hervorheben","Argumente für die Kandidatenvorstellung vorbereiten","Branche und Rolle in die Formulierung einbeziehen","Aufbau, Länge und Tonalität individuell einstellen"]}, en:{tagline:"Creates concise highlights explaining why a candidate fits a specific project.",capabilities:["Highlight relevant experience instead of requiring full CV review","Prepare key arguments for candidate presentations","Include industry and role context","Customize structure, length and tone"]}},
  { id:"ai-cv-formatter", icon:LayoutTemplate, name:"AI CV Formatter", de:{tagline:"Standardisiert CVs inklusive Anonymisierung und Übersetzung zwischen Deutsch und Englisch.",capabilities:["Einheitliche Struktur für Kandidatenvorstellungen","CVs inklusive Unternehmen und Branchen anonymisieren","Gesamten CV per Klick übersetzen","Rohdaten in eine versandfertige Fassung überführen"]}, en:{tagline:"Standardizes CVs including anonymization and translation between German and English.",capabilities:["Create a consistent structure for candidate presentations","Anonymize CVs including companies and industries","Translate the complete CV with one click","Turn raw data into a presentation-ready version"]}},
  { id:"ai-project-brief", icon:Sparkles, name:"AI Project Brief", de:{tagline:"Aggregiert alle vertragsrelevanten Informationen aus Projekt, Kandidat und Kunde und erstellt daraus versandfertige Projekt- und Beraterverträge für Freelance-Einsätze.",capabilities:["Projekt-, Kandidaten- und Kundendaten automatisch zusammenführen","Alle relevanten Freelance-Parameter wie Laufzeit, Auslastung, Einsatzort und Raten berücksichtigen","Rahmen- bzw. Projektvertrag für den Kunden generieren","Beratervertrag für den Freelancer mit den passenden Projektkonditionen erstellen"]}, en:{tagline:"Aggregates all contract-relevant information from the project, candidate and client and generates ready-to-send client project contracts and freelancer agreements.",capabilities:["Automatically combine project, candidate and client data","Include key freelance parameters such as term, workload, location and rates","Generate the client framework or project agreement","Generate the freelancer agreement with the correct assignment conditions"]}},
  { id:"ai-project-report", icon:Presentation, name:"AI Project Report", de:{tagline:"Erstellt Projektreports mit Kandidaten, Interviews, Statusänderungen, Absagegründen und Kennzahlen.",capabilities:["Kandidaten und Stati eines Projekts zusammenfassen","Interviews und Feedback sichtbar mitführen","Projektbezogene KPIs automatisch ausgeben","Gesprächsgrundlage für Kundenupdates erstellen"]}, en:{tagline:"Creates project reports covering candidates, interviews, status changes, rejection reasons and KPIs.",capabilities:["Summarize candidates and project statuses","Include interviews and feedback","Generate project-specific KPIs","Create a clear basis for client updates"]}},
  { id:"ai-company-status-report", icon:Kanban, name:"AI Company Status Report", de:{tagline:"Fasst laufende Kundenprojekte, Kandidatenstati und Interviews auf Account-Ebene zusammen.",capabilities:["Mehrere Suchmandate in einer Account-Sicht bündeln","Kandidatenstatus projektübergreifend nachvollziehen","Interviewhistorie zusammenfassen","Wöchentliche Kundenabstimmungen schneller vorbereiten"]}, en:{tagline:"Summarizes active client projects, candidate statuses and interviews at account level.",capabilities:["Combine multiple searches in one account view","Track candidate status across projects","Summarize interview history","Prepare recurring client updates faster"]}},
  { id:"ai-job-post-builder", icon:Briefcase, name:"AI Job Post Builder", de:{tagline:"Erstellt anonymisierte, publikationsreife Stellenanzeigen direkt aus den Mandatsdaten.",capabilities:["Rolle, Anforderungen und Rahmenbedingungen automatisch verarbeiten","Sensible Kundendaten anonymisieren","Texte für Jobbörsen und Karriereseiten vorbereiten","Stil, Struktur und Tonalität einheitlich halten"]}, en:{tagline:"Creates anonymized, publication-ready job ads directly from project data.",capabilities:["Process role, requirements and conditions automatically","Anonymize sensitive client information","Prepare copy for job boards and career pages","Keep style, structure and tone consistent"]}},
  { id:"ai-company-enricher", icon:Globe, name:"AI Company Enricher", de:{tagline:"Ergänzt Unternehmensprofile automatisch um strukturierte Firmendaten aus öffentlichen Quellen.",capabilities:["Branche, Größe und Geschäftsmodell recherchieren","Profilfelder statt Freitext befüllen","BD-Vorbereitung mit belastbaren Unternehmensinformationen unterstützen","Kundenakten schneller vervollständigen"]}, en:{tagline:"Enriches company profiles with structured company data from public sources.",capabilities:["Research industry, size and business model","Populate structured profile fields","Support business development with relevant company facts","Complete client records faster"]}},
  { id:"ai-signature-parser", icon:FileSignature, name:"AI Signature Parser", de:{tagline:"Liest Kontaktdaten aus E-Mail-Signaturen aus und bereitet sie strukturiert zur Übernahme vor.",capabilities:["Name, Rolle, Telefon, E-Mail und Socials erkennen","Vorschau vor dem Speichern anzeigen","Kontakte mit einem Klick in plyce anlegen","Datenqualität aus laufender Korrespondenz verbessern"]}, en:{tagline:"Extracts contact data from email signatures and prepares it for structured import.",capabilities:["Detect name, role, phone, email and social profiles","Show a preview before saving","Create contacts in plyce with one click","Improve data quality from everyday correspondence"]}},
  { id:"ai-recorder", icon:Mic, name:"AI Recorder", de:{tagline:"Macht Texteingabe per Diktat überall dort möglich, wo in plyce geschrieben wird, und bereitet den gesprochenen Inhalt automatisch im persönlich konfigurierten Schreibstil auf.",capabilities:["E-Mails, Tasks, Recruiter-Kommentare und weitere Textfelder per Spracheingabe befüllen","Gesprochenen Rohtext automatisch strukturieren und sprachlich verbessern","Persönlich konfigurierbaren Schreibstil auf die Texte anwenden","Schneller professionelle Texte erstellen, ohne sie vollständig tippen zu müssen"]}, en:{tagline:"Enables dictation anywhere text is written in plyce and automatically turns spoken input into polished copy using the user's configurable personal writing style.",capabilities:["Dictate emails, tasks, recruiter comments and other text fields","Automatically structure and improve raw spoken input","Apply a configurable personal writing style","Create professional copy faster without typing it from scratch"]}},
  { id:"ai-summary", icon:FileText, name:"AI Summary", de:{tagline:"Fasst umfangreiche Aktivitäts- und Kommunikationshistorien bei Projekten, Unternehmen, Kandidaten und Kontakten in wenigen Zeilen zusammen.",capabilities:["E-Mails, Aktivitäten, Kommentare und weitere Historieneinträge aggregieren","Auch sehr lange Historien mit hunderten Einträgen kompakt zusammenfassen","Wichtige Entwicklungen, Entscheidungen und letzte Kontakte hervorheben","Sofort verständlich machen, was bisher passiert ist, ohne die komplette Historie lesen zu müssen"]}, en:{tagline:"Summarizes extensive activity and communication histories across projects, companies, candidates and contacts into a few concise lines.",capabilities:["Aggregate emails, activities, comments and other history entries","Condense even histories with hundreds of entries","Highlight key developments, decisions and recent interactions","Show what has happened at a glance without reading the full history"]}},
  { id:"ai-meeting-tracker", icon:Video, name:"AI Meeting Tracker", beta:true, de:{tagline:"Erkennt Meetings aus Google Meet und Microsoft Teams automatisch, analysiert sie und ordnet sie dem richtigen Datensatz zu.",capabilities:["Notizen und Transkripte in Google Drive und OneDrive erkennen","Relevante Inhalte und Kernaussagen extrahieren","Meeting automatisch Kandidat oder Kontakt zuordnen","Zusammenfassung als Aktivität im Profil speichern"]}, en:{tagline:"Automatically detects Google Meet and Microsoft Teams meetings, analyzes them and assigns them to the correct record.",capabilities:["Detect notes and transcripts in Google Drive and OneDrive","Extract relevant content and key statements","Assign meetings to the right candidate or contact","Store the summary as an activity in the profile"]}},
];

export const aiAgentsNav = agents.map(({ id, name }) => ({ id, title: name }));

const AIAgentsPage = () => {
  const { pathname } = useLocation();
  const isEnglish = pathname.startsWith("/en/");
  const lang: "de" | "en" = isEnglish ? "en" : "de";
  return <div className="min-h-screen pt-24">
    <section className="py-16 md:py-24 section-padding"><div className="container-tight text-center">
      <ScrollReveal delay={80}><h1 className="text-4xl md:text-5xl lg:text-6xl font-extrabold tracking-tight leading-snug pb-2 mb-3 text-gradient-hero text-balance">{isEnglish ? "Focus on what matters" : "Konzentriere dich auf das Wesentliche"}<br />{agents.length} AI Agents {isEnglish ? "take care of the rest" : "erledigen den Rest"}</h1></ScrollReveal>
      <ScrollReveal delay={160}><p className="mt-6 text-lg text-muted-foreground text-center max-w-2xl mx-auto leading-relaxed">{isEnglish ? "Choose the AI setup that fits your requirements. OpenAI or Mistral, depending on data protection, data location and performance needs." : "Ihre Präferenz entscheidet. OpenAI oder Mistral, passend zu DSGVO, Datenstandort und Performance-Anforderungen."}</p></ScrollReveal>
    </div></section>
    <section className="pb-20 section-padding"><div className="container-tight space-y-6 md:space-y-8">{agents.map((agent,i)=>{const copy=agent[lang];return <ScrollReveal key={agent.id}><article id={agent.id} className="scroll-mt-28 rounded-2xl border border-border/50 bg-card overflow-hidden hover:shadow-lg hover:border-primary/20 transition-all duration-300"><div className="p-8 md:p-10"><div className="flex flex-col md:flex-row gap-6 md:gap-10"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary-light shrink-0"><agent.icon className="h-7 w-7 text-primary" /></div><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold tracking-tight">{agent.name}</h2><span className="text-xs font-medium text-primary bg-primary-light px-2 py-0.5 rounded-full">Agent #{i+1}</span>{agent.beta&&<span className="text-xs font-semibold text-primary bg-primary-light/60 border border-primary/30 px-2 py-0.5 rounded-full uppercase">Beta</span>}</div><p className="text-sm font-medium text-muted-foreground leading-relaxed mt-2">{copy.tagline}</p><div className="mt-4 border-t border-border/50 pt-4 grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-2.5">{copy.capabilities.map(cap=><div key={cap} className="flex items-start gap-2 text-sm"><div className="h-1.5 w-1.5 rounded-full bg-primary mt-1.5 shrink-0"/><span className="text-muted-foreground leading-relaxed">{cap}</span></div>)}</div></div></div></div></article></ScrollReveal>})}</div></section>
    <section className="py-20 section-padding"><div className="container-tight"><div className="rounded-3xl bg-foreground p-12 md:p-16 text-center"><h2 className="text-3xl md:text-4xl font-bold text-primary-foreground tracking-tight mb-8">{isEnglish ? "Experience all AI Agents live" : "Alle AI Agents live erleben"}</h2><Button variant="hero" size="lg" type="button" className="border-2 border-primary-foreground/25 bg-transparent text-primary-foreground hover:bg-primary-foreground/10" onClick={()=>window.dispatchEvent(new Event("plyce-open-demo-modal"))}>Request Demo <ArrowRight className="h-4 w-4"/></Button></div></div></section>
  </div>;
};
export default AIAgentsPage;
